# Generated by Django 5.2.6 on 2025-09-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mailings", "0001_initial"),
        ("messages_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="messages_app.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
