# Generated by Django 5.2.6 on 2025-09-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_country_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default.png",
                upload_to="avatars/",
                verbose_name="Аватар",
            ),
        ),
    ]
